/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.MALArticleContainer;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArticleControllerApi
 */
@Ignore
public class ArticleControllerApiTest {

    private final ArticleControllerApi api = new ArticleControllerApi();

    
    /**
     * Return article
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getArticleUsingGETTest() throws ApiException {
        String id = null;
        MALArticleContainer response = api.getArticleUsingGET(id);

        // TODO: test validations
    }
    
}
