/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MALEditor
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-17T19:20:51.858+02:00")
public class MALEditor {
  @SerializedName("email")
  private String email = null;

  @SerializedName("hidePicture")
  private Boolean hidePicture = null;

  @SerializedName("hsEditor")
  private Boolean hsEditor = null;

  @SerializedName("name")
  private String name = null;

  public MALEditor email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public MALEditor hidePicture(Boolean hidePicture) {
    this.hidePicture = hidePicture;
    return this;
  }

   /**
   * Get hidePicture
   * @return hidePicture
  **/
  @ApiModelProperty(value = "")
  public Boolean getHidePicture() {
    return hidePicture;
  }

  public void setHidePicture(Boolean hidePicture) {
    this.hidePicture = hidePicture;
  }

  public MALEditor hsEditor(Boolean hsEditor) {
    this.hsEditor = hsEditor;
    return this;
  }

   /**
   * Get hsEditor
   * @return hsEditor
  **/
  @ApiModelProperty(value = "")
  public Boolean getHsEditor() {
    return hsEditor;
  }

  public void setHsEditor(Boolean hsEditor) {
    this.hsEditor = hsEditor;
  }

  public MALEditor name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MALEditor maLEditor = (MALEditor) o;
    return Objects.equals(this.email, maLEditor.email) &&
        Objects.equals(this.hidePicture, maLEditor.hidePicture) &&
        Objects.equals(this.hsEditor, maLEditor.hsEditor) &&
        Objects.equals(this.name, maLEditor.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, hidePicture, hsEditor, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MALEditor {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    hidePicture: ").append(toIndentedString(hidePicture)).append("\n");
    sb.append("    hsEditor: ").append(toIndentedString(hsEditor)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

