/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MALPicture;
import java.io.IOException;

/**
 * MALVideo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-17T19:20:51.858+02:00")
public class MALVideo {
  @SerializedName("crossbowId")
  private String crossbowId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("runtime")
  private Integer runtime = null;

  @SerializedName("thumbnail")
  private MALPicture thumbnail = null;

  @SerializedName("title")
  private String title = null;

  public MALVideo crossbowId(String crossbowId) {
    this.crossbowId = crossbowId;
    return this;
  }

   /**
   * Get crossbowId
   * @return crossbowId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCrossbowId() {
    return crossbowId;
  }

  public void setCrossbowId(String crossbowId) {
    this.crossbowId = crossbowId;
  }

  public MALVideo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MALVideo runtime(Integer runtime) {
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @ApiModelProperty(value = "")
  public Integer getRuntime() {
    return runtime;
  }

  public void setRuntime(Integer runtime) {
    this.runtime = runtime;
  }

  public MALVideo thumbnail(MALPicture thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @ApiModelProperty(required = true, value = "")
  public MALPicture getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(MALPicture thumbnail) {
    this.thumbnail = thumbnail;
  }

  public MALVideo title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MALVideo maLVideo = (MALVideo) o;
    return Objects.equals(this.crossbowId, maLVideo.crossbowId) &&
        Objects.equals(this.id, maLVideo.id) &&
        Objects.equals(this.runtime, maLVideo.runtime) &&
        Objects.equals(this.thumbnail, maLVideo.thumbnail) &&
        Objects.equals(this.title, maLVideo.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crossbowId, id, runtime, thumbnail, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MALVideo {\n");
    
    sb.append("    crossbowId: ").append(toIndentedString(crossbowId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

